p.o = {};
p.o.iOS = ua.match(/iPhone|iPad|iPod|Apple-iPhone/i) != null;
p.o.ANDROID = ua.match(/Android/i) != null;
p.o.OSX = ua.match(/Macintosh|Intel Mac OS X/i) != null;
p.o.WINDOWS = ua.match(/Windows|Windows NT/i) != null;
p.o.WINDOWS_PHONE = ua.match(/Windows Phone/i) != null;
p.o.LINUX = ua.match(/Linux|X11/i) != null;
p.o.UBUNTU = ua.match(/Ubuntu/i) != null;
p.o.PLAYSTATION = ua.match(/PlayStation/i) != null;
p.o.XBOX = ua.match(/Xbox|XBOX_ONE_ED|Xbox One/i) != null;
p.o.BLACKBERRY = ua.match(/Blackberry|BB/i) != null;
p.o.CHROMECAST = ua.match(/CrKey/i) != null;
p.o.CHROME_OS = ua.match(/CrOS/i) != null;
p.o.PS4 = ua.match(/PlayStation 4/i) != null;
p.o.PSVITA = ua.match(/PlayStation Vita/i) != null;
p.o.XBOX_ONE = ua.match(/Xbox One/i) != null;
p.o.XBOX_ONE_S = ua.match(/XBOX_ONE_ED/i) != null;
p.o.NINTENDO = ua.match(/Nintendo/i) != null;
p.o.N3DS = ua.match(/Nintendo 3DS/i) != null;
p.o.WII_U = ua.match(/Nintendo WiiU/i) != null;
p.o.FIRE_TV = ua.match(/AFTS/i) != null;
p.o.ROKU_ULTRA = ua.match(/Roku4640X/i) != null;
p.o.ROKU = ua.match(/Roku/i) != null;
p.o.NEXUS_PLAYER = ua.match(/Nexus Player/i) != null;
p.o.MINIX_NEO_X5 = ua.match(/NEO-X5/i) != null;
p.o.APPLE_TV = ua.match(/AppleTV/i) != null;
p.o.KINDLE = ua.match(/Kindle/i) != null;
