p.o = {};
p.o.iOS = navigator.userAgent.match(/iPhone|iPad|iPod|Apple-iPhone/i) != null;
p.o.ANDROID = navigator.userAgent.match(/Android/i) != null;
p.o.OSX = navigator.userAgent.match(/Macintosh|Intel Mac OS X/i) != null;
p.o.WINDOWS = navigator.userAgent.match(/Windows|Windows NT/i) != null;
p.o.WINDOWS_PHONE = navigator.userAgent.match(/Windows Phone/i) != null;
p.o.LINUX = navigator.userAgent.match(/Linux|X11/i) != null;
p.o.UBUNTU = navigator.userAgent.match(/Ubuntu/i) != null;
p.o.PLAYSTATION = navigator.userAgent.match(/PlayStation/i) != null;
p.o.XBOX = navigator.userAgent.match(/Xbox|XBOX_ONE_ED|Xbox One/i) != null;
p.o.BLACKBERRY = navigator.userAgent.match(/Blackberry|BB/i) != null;
p.o.CHROMECAST = navigator.userAgent.match(/CrKey/i) != null;
p.o.CHROME_OS = navigator.userAgent.match(/CrOS/i) != null;
p.o.PS4 = navigator.userAgent.match(/PlayStation 4/i) != null;
p.o.PSVITA = navigator.userAgent.match(/PlayStation Vita/i) != null;
p.o.XBOX_ONE = navigator.userAgent.match(/Xbox One/i) != null;
p.o.XBOX_ONE_S = navigator.userAgent.match(/XBOX_ONE_ED/i) != null;
p.o.NINTENDO = navigator.userAgent.match(/Nintendo/i) != null;
p.o.N3DS = navigator.userAgent.match(/Nintendo 3DS/i) != null;
p.o.WII_U = navigator.userAgent.match(/Nintendo WiiU/i) != null;
p.o.FIRE_TV = navigator.userAgent.match(/AFTS/i) != null;
p.o.ROKU_ULTRA = navigator.userAgent.match(/Roku4640X/i) != null;
p.o.ROKU = navigator.userAgent.match(/Roku/i) != null;
p.o.NEXUS_PLAYER = navigator.userAgent.match(/Nexus Player/i) != null;
p.o.MINIX_NEO_X5 = navigator.userAgent.match(/NEO-X5/i) != null;
p.o.APPLE_TV = navigator.userAgent.match(/AppleTV/i) != null;
p.o.KINDLE = navigator.userAgent.match(/Kindle/i) != null;
